### ISSUE TITLE
could not find function "renameColumn

### ISSUE THREAD

**Issue by simang5c** [jmw86069/multienrichjam#1]
Hi, I tried converting S4 object to the data frame and then tried reconverting it to the S4 class using "multienrichjam" package. I found the following error. Any help would be really appreciated.

library(DOSE)
data(geneList)
de <- names(geneList)[abs(geneList) > 2]

edo <- enrichDGN(de)
edo_df<-as.data.frame(edo)

library(multienrichjam)
test<-enrichDF2enrichResult(edo_df)

output: Error in renameColumn(enrichDF, from = c(keyColname, pvalueColname, geneColname),  :   could not find function "renameColumn"

**Comment by jmw86069** [comment]
Thank you for posting this issue! It was a bug in my R package code, calling a function from `jamba` without using the package prefix. I have converted the R code to call `jamba::renameColumn()` and fixed similar bugs in the package functions.

If you encounter similar errors, try loading those packages (jamba, colorjam, ComplexHeatmap) into your session. It shouldn't occur, but just in case. :)

To fix, reinstall multienrichjam:

```{r}
remotes::install_github("jmw86069/multienrichjam")
```

Also thanks for posting a reproducible example. I was able to test the input data, and confirm it works with the minimal steps. Even with only one enrichment as input.

```{r}
library(DOSE)
data(geneList)
de <- names(geneList)[abs(geneList) > 2]

edo <- enrichDGN(de)
edo_df <- as.data.frame(edo)

library(multienrichjam)
test <- enrichDF2enrichResult(edo_df)

mem <- multiEnrichMap(list(test=test));

# mem_plot_folio() makes several plots
mpf <- mem_plot_folio(mem)

# to make only one plot at a time, use do_which=2
mpf2 <- mem_plot_folio(mem, do_which=2)
```

I have not looked into converting the DOSE gene set identifiers to names; nor converting Entrez gene ID to gene symbol. But it seems the DOSE package has methods to do that. If you have questions there, let me know and I will look into it.

**Comment by simang5c** [comment]
Thanks!
