### ISSUE TITLE
Error in ans[ypos] <- rep(yes, length.out = len)[ypos] :    replacement has length zero

### ISSUE THREAD

**Issue by nickhir** [jmw86069/multienrichjam#4]
Hello,
I am using the `enrichDF2enrichResult` method to convert a result data frame I obtained with `webgestaltR` into a enrichResult.
using the following command:

```
enrichResult <- enrichDF2enrichResult(
  enrichDF = df,
  pvalueCutoff = 1,
  pAdjustMethod = "FDR",
  keyColname = "geneSet",
  pathGenes = "size",
  geneColname = "userId",
  geneHits = "overlap",
  geneDelim = ";",
  pvalueColname = "pValue")
```

This seems to work fine and there appear no error messages. However, when I try and use the resulting Large enrichResult, e.g. with `barplot` or `dotplot` from the  `clusterProfiler` or `enrichplot` package, I get the following error:
```
Error in ans[ypos] <- rep(yes, length.out = len)[ypos] : 
  replacement has length zero
```
Do you have any idea what might be the cause of this? 
These are the package versions I am using:
` enrichplot_1.10.1         clusterProfiler_3.18.0    multienrichjam_0.0.37.900 DOSE_3.16.0 `
I have also attached the table which I want to turn into the enrichResult.

[enrichment_results_1610716848.txt](https://github.com/jmw86069/multienrichjam/files/5836434/enrichment_results_1610716848.txt)

Cheers!

**Comment by jmw86069** [comment]
Thank you for the feedback!

I was able to trace the issue with `enrichplot::dotplot()` and the underlying function `enrichplot:::fortify.internal()` which requires the description column name to be `"Description"` with capital D. I did not realize there was such a requirement, but now that I know I will adjust `enrichDF2enrichResult()` accordingly.

I have updated `multienrichjam` to version `0.0.38.900` with a new argument `"descriptionColname"` to `enrichDF2enrichResult()`.

In version 37 and prior, you can work around the issue by renaming the column `"description"` to `"Description"`, for example like this:

```R
enrichResult@result <- jamba::renameColumn(enrichResult@result,
   from="description",
   to="Description")
```

After that change I am able to run both `dotplot()` and `barplot()`.

```R
library(multienrichjam)
df <- data.table::fread("enrichment_results_1610716848.txt",
   data.table=FALSE)
enrichResult <- enrichDF2enrichResult(
   enrichDF = df,
   pvalueCutoff = 1,
   pAdjustMethod = "FDR",
   keyColname = "geneSet",
   pathGenes = "size",
   geneColname = "userId",
   geneHits = "overlap",
   geneDelim = ";",
   pvalueColname = "pValue")
enrichResult@result <- jamba::renameColumn(enrichResult@result,
   from="description",
   to="Description")
dotplot(enrichResult)
barplot(enrichResult)
```

**Comment by nickhir** [comment]
Thank you very much for that quick responds, works like a charm!
